### ISSUE TITLE
File "\Simple-Spam-Bot-main\main.py", line 6, in <module>

### ISSUE THREAD

**Issue by Jonybtw** [Kareem-dev/Simple-Spam-Bot#1]
File "\Simple-Spam-Bot-main\main.py", line 6, in <module>
    from ttkthemes import ThemedTk
ModuleNotFoundError: No module named 'ttkthemes'

**Comment by Kareem-dev** [comment]
sorry for being late,
my bad, I forgot you have to install it before using it... I thought that it comes pre-install with python
just install the ttkthemes module using pip
I'll fix it now in the readme file. Thank you for notifying me
